#!/usr/bin/env zsh

. $HOME/.zshenv

# Grab all git submodules
cd `dirname $0` && git submodule update --init --recursive

# Install zplug if not already installed
ZPLUG_ROOT=$ZPLUG_HOME/repos/zplug/zplug
if [ ! -d "$ZPLUG_ROOT" ]; then
    echo Downloading zplug
    git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

# Install zsh bundles
zsh -ic "zplug install" </dev/null
zsh -ic "zplug update" </dev/null

# Install vim-plug if not already installed
VIMPLUG=$HOME/.vim/autoload/plug.vim
if [ ! -f "$VIMPLUG" ]; then
    echo Downloading vim-plug
    curl -fLo $VIMPLUG --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Set up neovim config symlinks
NVIM_CONFIG=${XDG_CONFIG_HOME:-$HOME/.config/}/nvim
NVIM_INIT=$NVIM_CONFIG/init.vim
mkdir -p $NVIM_CONFIG
if [ ! -e "$NVIM_INIT" ]; then
    ln -s $HOME/.vimrc $NVIM_INIT
fi
mkdir -p $NVIM_CONFIG/autoload
if [ ! -e "$NVIM_CONFIG/autoload/plug.vim" ]; then
    ln -s $HOME/.vim/autoload/plug.vim $NVIM_CONFIG/autoload/plug.vim
fi

# Update vim-plug and install plugins
which nvim 1>/dev/null && nvim -c "PlugUpgrade | PlugUpdate | qa"
which vim 1>/dev/null && vim -c "PlugUpgrade | PlugUpdate | qa"

