#!/bin/sh

# Grab all git submodules (mostly for antigen)
git submodule update --init --recursive

# Install zsh bundles
zsh -c "source $HOME/.zshbundles && antigen apply"

# Install dein.vim if not already installed
DEIN_PATH=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim
if [ ! -e "$DEIN_PATH" ]; then
    git clone https://github.com/Shougo/dein.vim $DEIN_PATH
fi

# Set up neovim config symlinks
NVIM_CONFIG=${XDG_CONFIG_HOME:-$HOME/.config/}/nvim
NVIM_INIT=$NVIM_CONFIG/init.vim
mkdir -p $NVIM_CONFIG
if [ ! -e "$NVIM_INIT" ]; then
    ln -s $HOME/.vimrc $NVIM_INIT
fi
